version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: railgo
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - ${PWD}:${PWD}:rw
    ports:
      - 8010:8000
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ${PWD}:${PWD}:rw
    ports:
      - '6379:6379'